### ISSUE TITLE
alpaca.getBarsV2 is not a function

### ISSUE THREAD

**Issue by chalupagrande** [alpacahq/alpaca-trade-api-js#128] opened 2021-03-30 03:08 UTC
following the Documentation: 
```
getBarsV2(
  symbol,
  
  {
    limit: number,
    start: date isoformat string yyyy-mm-ddThh:MM:ss-04:00,
    end: date isoformat string yyyy-mm-ddThh:MM:ss-04:00,
    timeframe: "1Min" | "1Hour" | "1Day"
  }
) => Promise<BarsObject>
```
Here is my code: 
```
const alpaca = new Alpaca({
    keyId: process.env.ALPACA_API_KEY_ID,
    secretKey: process.env.ALPACA_API_SECRET_KEY,
    paper: true,
    usePolygon: false
  })

alpaca.getBarsV2('GME', {
    limit: 100,
    start: new Date(Date.now() - 30 * 60 * 60 * 24 * 1000).toISOString(), // 30 days ago
    end: new Date().toISOString(),
    timeframe: '1Day',
})
```
Expected to get Bars. Got `alpaca.getBarsV2 is not a function`

**Comment by austin-wang** [comment] 2021-05-11 23:47
Hi @chalupagrande, can you confirm you're using version `v2.1.0` of the library?

**Comment by chalupagrande** [comment] 2021-05-13 04:15
@austin-wang I did not... I only had v2.0.0. Dumb mistake. Thanks!

**Comment by hudsonbl** [comment] 2021-05-17 21:46
```
const Alpaca = require('@alpacahq/alpaca-trade-api')
require('dotenv').config()

const alpaca = new Alpaca({
    keyId: process.env.API_KEY,
    secretKey: process.env.API_SECRET,
    paper: true,
    usePolygon: false,
})

module.exports = alpaca
```
```
const alpaca = require("./config/alpaca");
async function getBars() {
    
    try {
        await alpaca.getBarsV2('GME', {
            limit: 100,
            start: new Date(Date.now() - 30 * 60 * 60 * 24 * 1000).toISOString(), // 30 days ago
            end: new Date().toISOString(),
            timeframe: '1Day',
        }, alpaca.configuration
        )
        .then((response) => {
            console.log("RES: ", response)
        })
    } catch(err) {
        console.log("errr", err);
    }
  alpaca.lastQuote('AAPL').then((response) => {
        console.log(response)
    })
}

getBars()
```
I also got alpaca.getBarsV2 is not a function and I am using v2.1.0. @chalupagrande was there any addition you did to make it work? I checked node_modules for the function and saw that it is indeed being added to Alpaca.prototype within @alpacahq\alpaca-trade-api\alpaca-trade-api.js line 113.

**Comment by JasonSimms** [comment] 2021-05-26 16:43
Did this get fixed, are there any usable examples?  So frustrating, I've got response 422 using these code examples

**Comment by hudsonbl** [comment] 2021-05-26 22:26
For the time being if you're using node.js. Here is my current solution. I decided to do the call manually.
```
const getHistoricalTradeData = async (symbol) => {
    
    // This gets the date time from wherever the server is located
    const { startDate, endDate } = getDateForHistoricalData(30);
    console.log("Start: ", startDate)
    console.log("End: ", endDate);
    const url = `https://data.alpaca.markets/v2/stocks/${symbol}/trades`
    const options = {
        headers: {
           'APCA-API-KEY-ID': process.env.API_KEY,
           'APCA-API-SECRET-KEY': process.env.API_SECRET
        },
        params: {
            start: startDate,
            end: endDate,
            limit: 1000,
        }
    }
    return new Promise(async (resolve, reject) => {
        await axios.get(url, options)
        .then((response) => {
            // Map response to my data format
            const result = response.data.trades.map((asset, idx) => [Date.parse(asset.t), asset.p])
            resolve(result);
        })
        .catch((err) => {
            console.log("err: ", err);
            reject([]);
        });
    })
}
```

**Comment by daweedco** [comment] 2021-11-24 17:26
Hello still the same error for me ?

**Comment by noramehesz** [comment] 2021-11-29 10:02
Hello!
`getBarsV2` is a generator function, using `await` before the call is not proper here. You can use tests like examples. 
```
let resp = alpaca.getBarsV2("AAPL", {
      start: "2021-02-01",
      end: "2021-02-10",
      limit: 2,
      timeframe: "1Day",
      adjustment: alpaca.adjustment.RAW,
});
const bars = [];

for await (let b of resp) {
     bars.push(b);
}
```    
@chalupagrande @hudsonbl  @daweedco please feel free to ask if you have any question!

**Comment by SyntaxisCS** [comment] 2022-01-02 19:52
> Hello! `getBarsV2` is a generator function, using `await` before the call is not proper here. You can use tests like examples.
> 
> ```
> let resp = alpaca.getBarsV2("AAPL", {
>       start: "2021-02-01",
>       end: "2021-02-10",
>       limit: 2,
>       timeframe: "1Day",
>       adjustment: alpaca.adjustment.RAW,
> });
> const bars = [];
> 
> for await (let b of resp) {
>      bars.push(b);
> }
> ```
> 
> @chalupagrande @hudsonbl @daweedco please feel free to ask if you have any question!

Still the same issue, getBarsV2 is not a function.

**Comment by noramehesz** [comment] 2022-01-03 09:51
@SyntaxisCS I know it was already asked, but with the newest version of the SDK? If yes send me your whole code, or send me a message on community slack. The code above is working for me.

**Comment by Luk-z** [comment] 2022-01-09 11:27
@noramehesz I think it's more clear writing the exact type of getBarsV2 return value: "AsyncGenerator<AlpacaBar, void, unknown>" or "AsyncGenerator<AlpacaBar, void, unknown>" will be good solutions. 
"Promise<BarsObject>" it's definitely wrong and confusing.

I've created this PR https://github.com/alpacahq/alpaca-trade-api-js/pull/183

**Comment by Henry12116** [comment] 2022-03-14 23:58
Tried with versions 2.12.0 and 2.12.1.

When I do:
```javascript
const Alpaca = require('@alpacahq/alpaca-trade-api')
const alpaca = new Alpaca({
  keyId: 'MINE',
  secretKey: 'ALSOMINE',
  paper: true,
})
console.log(Object.keys(alpaca));
```

```bash
[
  'httpRequest',
  'dataHttpRequest',
  'getAccount',
  'updateAccountConfigurations',
  'getAccountConfigurations',
  'getAccountActivities',
  'getPortfolioHistory',
  'getPositions',
  'getPosition',
  'closeAllPositions',
  'closePosition',
  'getCalendar',
  'getClock',
  'getAssets',
  'getAsset',
  'getOrders',
  'getOrder',
  'getOrderByClientId',
  'createOrder',
  'replaceOrder',
  'cancelOrder',
  'cancelAllOrders',
  'getWatchlists',
  'getWatchlist',
  'addWatchlist',
  'addToWatchlist',
  'updateWatchlist',
  'deleteWatchlist',
  'deleteFromWatchlist',
  'configuration',
  'data_ws',
  'trade_ws',
  'data_stream_v2',
  'adjustment',
  'crypto_stream_v2',
  'news_stream'
]
```
`getBarsV2`, `lastTrade`, and `lastQuote`  are all missing.

**Comment by noramehesz** [comment] 2022-03-22 08:28
You shouldn't get back the functions because they aren't keys of the Alpaca instance, but if you try with `console.log(typeof alpaca.getBarsV2);` it returns `function`. If you run your code in debug mode and put a breakpoint anywhere after you created the Alpaca object you can get all the information about it, this function will be on the `proto` of it. 
It would be helpful for me if you give me a minimal reproducible code, and tell me the way you run it, and the node version you using. I would like to reproduce your issue at my end. @Henry12116

**Comment by SyntaxisCS** [comment] 2022-04-06 13:38
getBarsV2, lastTrade, and lastQuote do not work whatsoever. My best workaround for getBarsV2 is using getMultiBarsV2 which is not on the documentation and it accepts an array. You then pass only one ticker in the array (alpaca.getMultiBarsV2(["GOOG"])) this is my best workaround and is the only way I can actually get the bars as those 3 functions keep returning the error of does not exist. They just aren't there.

**Comment by drew887** [comment] 2022-04-06 14:17
Ah I just realized I think the source of some confusion here, the README still lists `lastTrade` and `lastQuote` as the functions you should be using here however I believe it should be `latestTrade` and `latestQuote` now :disappointed: 

However I still request a reproducible case for getBarsV2 not working as that should definitely still be working :thinking:

**Comment by drew887** [comment] 2022-04-28 15:01
Hey its been quiet here for a while and no one was able to provide proof that getBarsV2 doesn't work on the latest versions of the SDK so I am going to close this one out. Please re-open if you can provide an example of it not being available

**Closed by drew887** 2022-04-28 15:01 UTC

**Comment by michaeljwright** [comment] 2022-05-10 17:04
It still doesn't appear to work properly (or as documented). Certainly doesn't work close to the V1.  I had to solve it via a direct API call to your V2 endpoint and then parse the response data accordingly.

Call to API endpoint (V2):
```
const stocks = ["AAPL", "TSL"];
let until = new Date()
let start = new Date();
    await fetch(
      "https://data.alpaca.markets/v2/stocks/bars?symbols=" +
        stocks.toString() +
        "&start=" +
        start.toISOString().split('T')[0] +
        "T00:00:00Z&end=" +
        until +
        "&timeframe=1Min",
      {
        method: "GET",
        headers: {
          "Apca-Api-Key-Id": process.env.API_KEY,
          "Apca-Api-Secret-Key": process.env.SECRET_API_KEY,
        },
      }
    )
      .then((response) => {
        if (response.status >= 400) {
          console.log("ERROR: AlpacaMarketDataV2");
        }
        return response.json();
      })
      .then(async (response) => {
        if (response) {
          // do something with response and parse the response data to how you need it
        }
      })
      .catch(function (err) {
        console.log("ERROR: AlpacaMarketDataV2");
        console.error(err);
      });
```

Example of how to parse the response data:
```
const stocks = ["AAPL", "TSL"];
let stockData = [];
  let openValues = [];
  let closeValues = [];
  let highValues = [];
  let lowValues = [];
  let volumeValues = [];

  _.forOwn(stocks, (stock) => {
    if (!isBacktest) {
      openValues = _.map(response.bars[stock], (bar) => bar.o);
      closeValues = _.map(response.bars[stock], (bar) => bar.c);
      highValues = _.map(response.bars[stock], (bar) => bar.h);
      lowValues = _.map(response.bars[stock], (bar) => bar.l);
      volumeValues = _.map(response.bars[stock], (bar) => bar.v);
    }

    stockData.push({
      symbol: stock,
      subject: stock,
      lastOrder: lastOrder,
      signals: [], // list of signals (buy/sell) based on algos
      closeValues: closeValues,
      openValues: openValues,
      highValues: highValues,
      lowValues: lowValues,
      volumeValues: volumeValues,
      price: 0,
    });
  });
```

For more fun with trading bots, please visit https://github.com/michaeljwright/robobull-trading-bot

**Comment by fehoffcial** [comment] 2023-06-23 09:23
Pessoal pra quem vai esta com problema como se ultilizar API Alcapa  com JavaScript e Nodejs.
![Screenshot from 2023-06-23 10-20-31](https://github.com/alpacahq/alpaca-trade-api-js/assets/102194131/9375da54-20cf-41e2-836a-45bae9af0914)

```javascript
const Alpaca = require('@alpacahq/alpaca-trade-api')
let API_KEY = "SUA KEY API"
let API_SECRET = "SUA KEY API API_SECRET"
async function asyncCall() {
    const alpaca = new Alpaca({
        keyId: API_KEY,
        secretKey: API_SECRET,
        paper: true,
        usePolygon: false,
    })
  console.log(alpaca.getBarsV2);
  console.log(alpaca.getLatestTrade);
  console.log(alpaca.getLatestQuote);
  const bars = alpaca.getBarsV2("AAPL", {
    start: "2022-06-23",
    end: "2022-06-23",
    timeframe: alpaca.newTimeframe(30, alpaca.timeframeUnit.MIN),
    limit: 2,
  });
  const got = [];
  for await (let b of bars) {
    got.push(b);
  }
  console.log(got);
  const news = await alpaca.getNews("BTC");
  console.log(news[0]);
  }
  
asyncCall();
```
